# action.yml
name: 'Clean Repo Artifacts'
description: 'Clean Repository artifacts except excluded one'
  exclude:
    description: 'File pattern to exclude'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.exclude }}
